# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20161121_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='版块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='版块管理员名称'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版块名称'),
        ),
    ]
