# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161122_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_update_timestamp',
        ),
    ]
