# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20161122_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
